config/routes.rb
Rails.application.routes.draw do
  get 'register' => 'users#new'
  post 'register' => 'users#create'


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  resources :reservations do
    collection do
      get 'day', to: 'reservations#day'
    end
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user

  validate :cannot_overlap
  validates :starts_at, presence: true
  validates :name, presence: true

  def cannot_overlap
    cnt = Reservation.where('starts_at <= ? AND ends_at > ?', starts_at, starts_at).count
    if cnt > 0
      errors.add :starts_at, 'A booking already exists at this time, please select another time.'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reservations

  validates :username, presence: true
  validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/reservations_controller.rb
require 'date'

class ReservationsController < ApplicationController
  def index
    month = Date.today.strftime '%m'
    @reservations = Reservation.where month: month
    @weathers
  end

  def show
    @reservation = Reservation.find params[:id]
  end

  def new
    authorize

    @reservation = Reservation.new
    @reservation.starts_at = params[:date]
  end

  def create
    authorize

    @reservation = Reservation.new reservation_params
    @reservation.user = current_user

    # Move to initializer? after_initialize?
    @reservation.year = @reservation.starts_at.year
    @reservation.month = @reservation.starts_at.month
    @reservation.day = @reservation.starts_at.day
    @reservation.ends_at = @reservation.starts_at + 2.hours

    if @reservation.save
      redirect_to reservation_path(@reservation)
    else
      render :new
    end
  end

  def day
    @date = Date.parse params[:day]
    @reservations = Reservation.where(year: @date.year, month: @date.month, day: @date.day).order :starts_at
    @weather = FetchWeather.for_day @date
  end

  private
    def reservation_params
      params.require(:reservation).permit(:name, :year, :month, :day, :starts_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by username: params[:login][:username]
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      redirect_to reservations_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new user_params

    if user.save
      session[:user_id] = user.id
      redirect_to reservations_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funeral</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= link_to 'HOME', reservations_path %>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer>
    <% if current_user %>
      You are logged in as <em><%= current_user.username %></em> |
      <%= link_to 'Log out', logout_path %>
    <% else %>
      You are not logged in. |
      <%= link_to 'Log in', login_path %>
    <% end %>
  </footer>
</body>
</html>

app/views/reservations/day.html.erb
<h1>Reservations on <%= @date.strftime('%d %B %Y') %></h1>

<% if @reservations.any? %>
  <% @reservations.each do |reservation| %>
      <h3><%= link_to reservation.name, reservation_path(reservation) %></h3>
      <p>
        Starts: <%= reservation.starts_at.strftime('%H:%M:%S') %>
      <p>
        Ends: <%= reservation.ends_at.strftime('%H:%M:%S') %>
  <% end %>
<% else %>
    There are no reservations today. Book in the next 20 minutes and get a 20% off coupon.
<% end %>

<h2>Weather</h2>
<% if @weather %>
    <p>Min temperature: <%= @weather['temp']['min'] %>
    <p>Max temperature: <%= @weather['temp']['max']%>

    <% @weather['weather'].each do |weather| %>
      <p>Weather: <%= weather['description'] %>
    <% end %>
<% else %>
    No weather data for this day (yet, or maybe never).
<% end %>

<h2>Booking</h2>
  <%= link_to 'BOOK', new_reservation_path({:date => @date}) %>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<%= month_calendar do |date| %>
    <div class="day">
      <p>
        <%= date %>
      <p>
        <% today = @reservations.select { |res| res.day == date.day} %>
        <%= link_to day_reservations_path(:day => date) do %>
          <%= pluralize today.length, 'reservations' %>
        <% end %>
    </div>
<% end %>

app/views/reservations/new.html.erb
<h1>Book a reservation</h1>

<%= form_for :reservation, url: reservations_path do |f| %>
    <% @reservation.errors.full_messages.each do |error| %>
        <div style="color:red">
          <%= error %>
        </div>
    <% end %>
  <p>
    <%= f.label :name, "Your cat's name" %>
    <%= f.text_field :name %>

  <p>
    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at, :value => @reservation.starts_at %>
    <small>Funeral will last 2 hours</small>

  <p>
    <%= f.submit 'Submit' %>
<% end %>

app/views/reservations/show.html.erb
<h1>In memory of <%= @reservation.name %></h1>
<p>
  He/she/it was a good cat. RIP in peace, <%= @reservation.name %>

<p>
  The funeral will begin on the day of <%= @reservation.starts_at.strftime('%d %B %Y') %>
  at exactly <%= @reservation.starts_at.strftime('%H:%M') %>, and will end two hours later, at
<%= @reservation.ends_at.strftime('%H:%M') %>. Be ready.

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for :user, url: register_path do |f| %>
    <p>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <p>
    <%= f.label :password %>
    <%= f.password_field :password %>

    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

    <p>
    <%= f.submit 'Register' %>
<% end %>